#################################################################################
#### summary the pile up file generated by the mpileup
#### validate at 20220525 by TianHua Liao
#################################################################################

import numpy as np
import pandas as pd
from tqdm import tqdm
import os
import pandas as pd

def main(bed_file,pileup_file):
    # bed_file = "DFL12_anno.bed"
    rows = [_.split('\t') for _ in open(bed_file).read().strip().split('\n')]
    anno2se = {row[-1]:(row[0],int(row[1]),int(row[2])) for row in rows}

    # pileup_file = './A9/A9.pileup'
    df = pd.read_csv(pileup_file,sep='\t')
    df.columns = ['chr','pos','base','depth','read bases','read quality']
    chr2df = {chr:df.loc[idx,:] for chr,idx in df.groupby('chr').groups.items()}
    anno2mean_depth = {}
    for anno,(chr,s,e) in tqdm(anno2se.items()):
        subdf = chr2df[chr]
        subdf = subdf.set_index('pos')
        mean_depth = subdf.loc[s:e,'depth'].mean()
        anno2mean_depth[anno] = mean_depth
    annodf = pd.DataFrame.from_dict(anno2mean_depth,orient='index')
    annodf.columns = ['mean depth']
    annodf.loc[:,'chr'] = [anno2se[_][0] for _ in annodf.index]
    annodf.to_csv(pileup_file.replace('.pileup','.pileup_annotations.csv'),sep='\t',index=1)
    #return annodf

if __name__ == '__main__':
    import sys
    bed_file,pileup_file = sys.argv[1:]
    main(bed_file,pileup_file)