res_cols = ["Sp_krkn_FinalCall", 'source', '科室', 'Oxf_ST.1', 'RES_PIP', 'RES_CRO', 'RES_IPM', 'RES_AMK', 'RES_TGC', 'RES_CIP', 'RES_SXT']
vf_cols = ["Sp_krkn_FinalCall", 'source', '科室', 'Oxf_ST.1', 'RES_IPM', 'RES_MEM']
med_cat = {'beta_lactams': ['SAM',
                            'PIP',
                            'TZP',
                            'CRO',
                            'CSL',
                            'CAZ',
                            'FEP',
                            'IPM',
                            'MEM'],
           'Aminoglycosides': ['AMK', 'GEN', 'MNO', 'TGC'],
           'Fluoroquinolones': ['CIP', 'LVX'],
           'Sulfonamide': ['SXT']}

group_dict = dict(group1=['40615', '41833', '41194', '39058', '40116', '42121', '42268'],
                  group2=['39292', '39502', '41296', '34960', '35082', '39054', '40067',
                          '42349', '43458', '37706', '37502', '35989', '39528'])
#
# OXAdict = {'OXA-106': 'OXA-51-like',
#            'blaOXA-117': 'OXA-51-like',
#            'blaOXA-120': 'OXA-51-like',
#            'blaOXA-213': 'OXA-213',
#            'blaOXA-23': 'OXA-23',
#            'blaOXA-51': 'OXA-51',
#            'blaOXA-66': 'OXA-51-like',
#            'blaOXA-69': 'OXA-51-like',
#            'blaOXA-72': 'OXA-40-like',
#            'blaOXA-75': 'OXA-51-like',
#            'blaOXA-98': 'OXA-51-like',
#            'OXA-217': 'OXA-51-like',
#            'OXA-384': 'OXA-51-like',
#            'OXA-421': 'OXA-213-like',
#            'blaOXA-123': 'OXA-51-like',
#            'blaOXA-407': 'OXA-51-like',
#            'blaOXA-408': 'OXA-51-like',
#            'blaOXA-430': 'OXA-51-like',
#            'blaOXA-500': 'OXA-213-like',
#            'blaOXA-694': 'OXA-51-like'}

vf2fun = {'ABZJ_00075': 'Capsule',
          'ABSDF0080': 'Capsule',
          'ACICU_00074': 'Capsule',
          'M3Q_299': 'Capsule',
          'M3Q_300': 'Capsule',
          'M3Q_296': 'Capsule',
          'M3Q_297': 'Capsule',
          'OOM_0626': 'Elongation factor Tu',
          "F7308_0636": 'Elongation factor Tu',
          'BJAB07104_00104': 'Capsule',
          'ACICU_00878': 'Heme',
          'ABZJ_01015': 'Heme',
          'ABK1_0104': 'Capsule',
          'ABZJ_01012': 'Heme',
          'ABD1_00540': 'Capsule',
          'ABD1_00560': 'Capsule',
          'ABD1_00570': 'Capsule',
          'ABK1_0082': 'Capsule',
          'ABK1_0083': 'Capsule',
          'ABK1_0085': 'Capsule',
          'ABK1_0086': 'Capsule',
          'ABK1_0087': 'Capsule',
          'ABK1_0089': 'Capsule',
          'ABK1_0090': 'Capsule',
          'ABK1_0091': 'Capsule',
          'ABK1_0099': 'Capsule',
          'ABK1_0100': 'Capsule',
          'ABSDF0073': 'Capsule',
          'ABSDF0074': 'Capsule',
          'ABTJ_03750': 'Capsule',
          'ABTJ_03758': 'Capsule',
          'ABTW07_0081': 'Capsule',
          'ABTW07_0082': 'Capsule',
          'ABTW07_0091': 'Capsule',
          'ABTW07_0092': 'Capsule',
          'ABTW07_0093': 'Capsule',
          'ABTW07_0094': 'Capsule',
          'ABTW07_0096': 'Capsule',
          'ABZJ_00078': 'Capsule',
          'ABZJ_00085': 'Capsule',
          'ABZJ_00086': 'Capsule',
          'ABZJ_00090': 'Capsule',
          'ABZJ_00096': 'Capsule',
          'ACICU_00072': 'Capsule',
          'ACICU_00073': 'Capsule',
          'ACICU_00077': 'Capsule',
          'ACICU_00083': 'Capsule',
          'BJAB07104_00106': 'Capsule',
          'BJAB0715_00096': 'Capsule',
          'BJAB0715_00109': 'Capsule',
          'BJAB0868_00089': 'Capsule',
          'M3Q_291': 'Capsule',
          'fnlA': 'Capsule',
          'ugd': 'Capsule',
          'wza': 'Capsule',
          'wzb': 'Capsule',
          'ABBFA_002691': 'Heme',
          'ABK1_0906': 'Heme',
          'ABZJ_01014': 'Heme',
          'BJAB0715_01030': 'Heme',

          'BJAB07104_00103': 'Capsule',
          'ACICU_00877': 'Heme',
          'ABSDF2280': 'Heme',
          'ACICU_00875': 'Heme',
          'BJAB07104_00105': 'Capsule',
          'ABBFA_003461': 'Capsule',
          'ABBFA_003451': 'Capsule',
          'ABBFA_003450': 'Capsule',
          'ABBFA_003448': 'Capsule',
          'ABAYE3808': 'Capsule',
          'AB57_0115': 'Capsule',
          'AB57_0094': 'Capsule',
          'AB57_0095': 'Capsule',
          'ABTJ_03747': 'Capsule',
          'ACICU_00091': 'Capsule',
          'galU': 'Capsule',
          'BJAB0868_00088': 'Capsule',
          'ACICU_00876': 'Heme',
          'ACICU_00874': 'Heme',
          'ABTW07_0100': 'Capsule',
          'ABZJ_01011': 'Heme',
          'M3Q_295': 'Capsule',
          'manB': 'Capsule',
          'M3Q_290': 'Capsule',
          'M3Q_285': 'Capsule',
          'M3Q_286': 'Capsule',
          'entE': 'Acinetobactin',
          'basF': 'Acinetobactin',
          'bauE': 'Acinetobactin',
          'bauD': 'Acinetobactin',
          'bauC': 'Acinetobactin',
          'bauF': 'Acinetobactin',
          'bauA': 'Acinetobactin',
          'bauB': 'Acinetobactin',
          'barB': 'Acinetobactin',
          'barA': 'Acinetobactin',
          'basJ': 'Acinetobactin',
          'basI': 'Acinetobactin',
          'basH': 'Acinetobactin',
          'basG': 'Acinetobactin',
          'basD': 'Acinetobactin',
          'basC': 'Acinetobactin',
          'basB': 'Acinetobactin',
          'basA': 'Acinetobactin',
          'Fphi_1039': 'Elongation factor Tu',
          'pgaC': 'PNAG (Polysaccharide poly-N-acetylglucosamine)',
          'pgaD': 'PNAG (Polysaccharide poly-N-acetylglucosamine)',
          'gi|89255449:1485851-1486723': 'succinate--CoA ligase subunit alpha',
          'gi|89255449:124674-126196': 'rRNA-16S ribosomal RNA',
          'gi|56707187:522503-523375': 'sucD',
          'gi|56707187:1378062-1379584': 'rRNA-16S ribosomal RNA',
          'gi|165975457:486015-487346': 'argininosuccinate synthase',
          "gi|77358697:149592-150776": "tufA",
          'plcD': 'Phospholipase D',
          'plc': 'Phospholipase C',
          'pgaB': 'PNAG (Polysaccharide poly-N-acetylglucosamine)',
          'pgaA': 'PNAG (Polysaccharide poly-N-acetylglucosamine)',
          'pbpG': 'PbpG',
          'ompA': 'Outer membrane protein',
          'lpxM': 'LPS',
          'lpxL': 'LPS',
          'lpxD': 'LPS',
          'lpxC': 'LPS',
          'lpxB': 'LPS',
          'lpxA': 'LPS',
          'lpsB': 'LPS',
          'bfmS': 'Two-component system',
          'bfmR': 'Two-component system',
          'adeH': 'AdeFGH efflux pump/transport autoinducer',
          'adeF': 'AdeFGH efflux pump/transport autoinducer',
          'adeG': 'AdeFGH efflux pump/transport autoinducer',
          'abaI': 'Quorum sensing',
          'csuA/B': 'Csu pili',
          'csuB': 'Csu pili',
          'csuE': 'Csu pili',
          'csuD': 'Csu pili',
          'csuA': 'Csu pili',
          'csuC': 'Csu pili',
          "pilG": 'Csu pili',
          'M3Q_302': 'Capsule',
          'ABAYE2875': 'Heme',
          'ABK1_0905': 'Heme',
          'M3Q_284': 'Capsule',
          'M3Q_283': 'Capsule',
          'M3Q_281': 'Capsule',
          'M3Q_282': 'Capsule',
          'M3Q_301': 'Capsule',
          'M3Q_298': 'Capsule',
          'M3Q_303': 'Capsule',
          'ABBFA_003459': 'Capsule',
          'ABBFA_003460': 'Capsule',
          'wzc': 'Capsule',
          'ABZJ_00094': 'Capsule',
          'ABZJ_00093': 'Capsule',
          'ABZJ_00091': 'Capsule',
          'ABZJ_00087': 'Capsule',
          'ABZJ_00080': 'Capsule',
          'ABZJ_00079': 'Capsule',
          'ABZJ_00077': 'Capsule',
          'ABTJ_03752': 'Capsule',
          'ABTJ_03751': 'Capsule',
          'ABTJ_03749': 'Capsule',
          'ABTJ_03743': 'Capsule',
          'ABSDF0072': 'Capsule',
          'ABSDF0071': 'Capsule',
          'ABSDF0070': 'Capsule',
          'ABD1_00590': 'Capsule',
          'ABSDF0067': 'Capsule',
          'ABTJ_03748': 'Capsule',
          'pgi': 'Capsule',
          'bap': 'Biofilm',
          'AB57_0990': 'Heme',
          'M3Q_1210': 'Heme',
          'AB57_0986': 'Heme',
          'hemO': 'Heme',
          'galE': 'Capsule',
          'gi|16271976:985887-987413': 'hktE',
          'M3Q_1212': 'Heme',
          'AB57_0993': 'Heme',
          'AB57_0992': 'Heme',
          'AB57_0989': 'Heme',
          'AB57_0984': 'Heme',
          'AB57_0988': 'Heme',
          "ABSDF2285": "Heme",
          "csrA": "carbon storage regulator",

          "gi|126207488:1587000-1587170": 'victors',
          "gi|56707187:523407-524570": "victors",

          'ACICU_00092': 'Capsule',
          'ACICU_00071': 'Capsule',
          'ABK1_0101': 'Capsule',
          'A1S_0060': 'Capsule',
          'A1S_0059': 'Capsule',
          'A1S_0058': 'Capsule',
          'A1S_0057': 'Capsule',
          'A1S_0056': 'Capsule',
          'A1S_0055': 'Capsule',
          'A1S_0054': 'Capsule',
          'A1S_0052': 'Capsule',
          'A1S_0053': 'Capsule',
          'ACICU_00088': 'Capsule',
          'BJAB07104_00088': 'Capsule',
          'A1S_0051': 'Capsule',
          'ABTW07_0095': 'Capsule',
          'ABK1_0102': 'Capsule',
          'abaR': 'Quorum sensing',
          "NaN": "nan"}

res2fun = {"NaN": "nan",
           'armA': 'Aminoglycosides',
           'strA': 'Aminoglycosides',
           'strB': 'Aminoglycosides',
           'aac3-Ia': 'Aminoglycosides',
           "ant(3'')-IIa": 'Aminoglycosides',
           "ant(3'')-I": 'Aminoglycosides',
           "ant(3'')-Ia": 'Aminoglycosides',
           "aph(3'')-Ib": 'Aminoglycosides',
           "aph(3'')-Ia": 'Aminoglycosides',
           'aph(6)-Id': 'Aminoglycosides',
           'ANT(3'')-IIa': 'Aminoglycosides',
           'aadA': 'Aminoglycosides',
           "Aph3''Ia": 'Aminoglycosides',
           'StrA': 'Aminoglycosides',
           'StrB': 'Aminoglycosides',
           'Aph3''Ia': 'Aminoglycosides',
           'Aac3-I': 'Aminoglycosides',
           'Aac6-Ib': 'Aminoglycosides',
           'Aac3-IIa': 'Aminoglycosides',
           "ANT(3'')-IIa": 'Aminoglycosides',
           'BlaA1': 'beta_lactams',
           'Mbl': 'beta_lactams',
           'BlaA2': 'beta_lactams',

           'blaADC-30': 'beta_lactams',
           'blaADC-58': 'beta_lactams',
           'blaADC-68': 'beta_lactams',
           'blaADC-73': 'beta_lactams',
           'blaADC-76': 'beta_lactams',
           'blaADC-77': 'beta_lactams',
           'blaADC-18': 'beta_lactams',
           'blaADC-2': 'beta_lactams',
           'blaADC-25': 'beta_lactams',
           'blaADC-6': 'beta_lactams',
           'blaADC-80': 'beta_lactams',
           'blaADC-155': 'beta_lactams',
           'blaADC-158': 'beta_lactams',
           'blaADC-165': 'beta_lactams',
           'blaADC-179': 'beta_lactams',
           'blaADC-57': 'beta_lactams',
           'blaADC-85': 'beta_lactams',
           'blaADC-867': 'beta_lactams',
           'blaA1': 'beta_lactams',
           'blaBlaA2': 'beta_lactams',
           'blaMbl': 'beta_lactams',
           'TEM-1D': 'beta_lactams',
           'TEM-12': 'beta_lactams',
           'blaOXA-106': 'beta_lactams',
           'blaOXA-117': 'beta_lactams',
           'blaOXA-120': 'beta_lactams',
           'blaOXA-213': 'beta_lactams',
           'OXA-23': 'beta_lactams',
           'blaOXA-51': 'beta_lactams',
           'blaOXA-66': 'beta_lactams',
           'blaOXA-69': 'beta_lactams',
           'OXA-72': 'beta_lactams',
           'blaOXA-98': 'beta_lactams',
           'OXA-217': 'beta_lactams',
           'OXA-384': 'beta_lactams',
           'blaOXA-421': 'beta_lactams',
           'blaOXA-123': 'beta_lactams',
           'blaOXA-407': 'beta_lactams',
           'blaOXA-408': 'beta_lactams',
           'blaOXA-430': 'beta_lactams',
           'blaOXA-500': 'beta_lactams',
           'blaOXA-694': 'beta_lactams',
           'ADC-5': 'beta_lactams',
           'OXA-75': 'beta_lactams',
           'TEM-1': 'beta_lactams',
           'tetB': 'Tetracyclines',
           'tetA': 'Tetracyclines',
           "Tet-39": 'Tetracyclines',
           'sul1': 'sulfanilamide',
           'sul2': 'sulfanilamide',
           'qacEdelta1': 'Disinfectant',
           "Zn-dependent_hydrolase": 'beta_lactams',
           "(Bla)beta-lactamase_class-C": 'beta_lactams',
           'catB8': 'Chloramphenicol',
           'abeM': 'Efflux Pump',
           'abeS': 'Efflux Pump',
           'adeA': 'Efflux Pump',
           'adeB': 'Efflux Pump',
           'adeC': 'Efflux Pump',
           'adeI': 'Efflux Pump',
           'adeJ': 'Efflux Pump',
           'adeK': 'Efflux Pump',
           "MsrE": 'Macrolide',
           "MphE": "Macrolide",
           'TetB': 'Efflux Pump',
           'adeL': 'Efflux Pump',
           'adeN': 'Efflux Pump',
           'adeR': 'Efflux Pump',
           'adeS': 'Efflux Pump'}

# t = {}
# for i in a:
#     cmd = """grep "%s" /tools/abricate/db/*/sequences""" % i
#     result = check_output(cmd,shell=True)
#     t[i] = result.decode('utf-8')
